version: '3.8'

services:
  pomodoro-pi:
    image: ghcr.io/david-engel-05/pomodoro-pi:latest
    container_name: pomodoro-pi
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      - SYSTEM_MONITOR_ENABLED=${SYSTEM_MONITOR_ENABLED:-true}
      - SYSTEM_MONITOR_INTERVAL=${SYSTEM_MONITOR_INTERVAL:-5000}
    volumes:
      # Mount for persistent local data (if not using Supabase)
      - pomodoro_data:/app/data
      # Mount for logs
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - pomodoro-network
    
    # Resource limits for Raspberry Pi
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    
    # Security settings
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pomodoro.rule=Host(`pomodoro.local`)"
      - "traefik.http.routers.pomodoro.entrypoints=web"
      - "traefik.http.services.pomodoro.loadbalancer.server.port=3000"

volumes:
  pomodoro_data:
    driver: local

networks:
  pomodoro-network:
    driver: bridge